### ISSUE TITLE
Spaces between assignments

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cos-guidelines#1]
I propose mandatory spaces before and after assignment:

```
set a = 1 
for i = 1:1:10 {
```

Instead of current:

```
for i=1:1:10
```

**Comment by tsafin** [comment]
This may be recommended as optional (as part of general recommendation to insert spaces around binary operators) but not mandatory. As you might reognized I didn't use it at the for example. That was oversight (because I do prefer to wrap it in spaces in most of the cases), but here it seemed quite legit
