### ISSUE TITLE
Using italics in COSQuickRef.md

### ISSUE THREAD

**Issue by isc-solon** [intersystems-ru/cos-guidelines#21]
The only remaining change to make in the cheat sheet is using italics for placeholders throughout. Especially after the last addition:
Set object = ##class(package.class).IndexNameOpen(value, concurrency, .status)
which should really be:
Set object = ##class(_package_._class_)._IndexName_Open(value, concurrency, .status)

But we have an **Issue**, because it's messy in md to use italics within code, and the output is not perfect:
`Set object = ##class(`_`package`_._`class`_)._`IndexName`_`Open(value, concurrency, .status)`

And I suppose that the best way to do global search and replace is to use GitHub Desktop and a different editor than the one in GitHub...

**Comment by tsafin** [comment]
Yes, it looks awkward in the markdown format. And IMHO creates more confusion than clarify anything. 
Most probably I'd not try to mess the code blocks at all. 

[At some moment you just have to say stop to all attempts to make markdown formatting to look exactly as your rich-text original document.]

**Comment by tsafin** [comment]
Although...

**Comment by eduard93** [comment]
Let's remove  `code formatting` for  all items. As I already said there's too much code in COSQuickRef.md to mark it visually. So instead of:
`Set object = ##class(`_`package`_._`class`_)._`IndexName`_`Open(value, concurrency, .status)`
we would have:
Set object = ##class(_package.class_)._IndexName_Open(value, concurrency, .status)

**Comment by tsafin** [comment]
There are 2 contradicting factors:
- code should be easily, visually distinguishable from the comments (that's why I marked it with backticks originally);
- and markdown formatting should still be easy to maintain, i.e. we could use the proposed trick or even worse, start to use html formatting, but it would be nightmare to maintain.

So rather not. This current subset is easy to maintain and still is easy to read in formatted way.

P.S.
Let us check other format types, beyond MarkDown, in the GitHub Wiki engine we have here. There might be better solution for this problem.
